apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-fsim
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kogm-tenant/rhtap-demo-app/hacbs-test-project-fsim@sha256:ed3e9a3827eddf031cea8a4948e866e0d2854ec8881e4f5d9ce5c34403794680
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
